#!/usr/bin/env bash
# Eight peers in one relay room. Runs ON the relay host.
#
# WHY THIS SHAPE
#
# MEMBERS_PER_ROOM has been 8 since 99846529d and the largest real game has been 3. Eight-way is
# not two-way with a bigger number: lockstep waits for the slowest peer, the join handshake is
# point-to-point, and the relay's unicast routing has only ever had to distinguish three addresses.
#
# ONE NAMESPACE PER PEER, NOT MULTI-INSTANCE. `initRelay` disables relay mode for multi-instance
# clients on macOS/Linux, because a per-instance 127.x bind collides with the wildcard bind relay
# mode needs. So running eight copies on one box the ordinary way silently drops them OFF the relay
# and onto a plain LAN - they would still play, still agree, and the run would prove nothing about
# the relay. A namespace gives each peer its own port table and keeps it in relay mode.
#
# PER-PEER XDG_DATA_HOME. The engine resolves its user data dir from XDG_DATA_HOME, then HOME
# (GlobalData.cpp). Peers write Network.ini and MapPreviews there during a run; eight sharing one
# directory race on those writes, and a corrupted read would present as a desync rather than as the
# file-level collision it is. Each peer gets its own directory with its own Options.ini.
#
# NO LocalVirtualIP AND NO RelayRoom. Every address is assigned by the relay and the room token is
# generated by the host, so this also exercises identity assignment at eight - the point where
# "assign the lowest free address" has to be right seven times, not once.
#
# Usage, on the relay host:
#   MAP='maps\killing fields\killing fields.map' FRAMES=1500 ./relay-8peer.sh
#
# Env:
#   PEERS     total peers incl. host   (default 8)
#   FRAMES    logic frames             (default 1500)
#   MAP       map path, backslashed    (default killing fields)
#   AI        -lanai spec, or empty    (default empty - eight humans fill the lobby)
#   GAME      game data dir            (default /root/gamedata)
#   RELAY_IP  relay address            (default 163.5.210.131)
#   OUT       results dir              (default timestamped under /root)

set -uo pipefail

PEERS="${PEERS:-8}"
FRAMES="${FRAMES:-1500}"
MAP="${MAP:-maps\\killing fields\\killing fields.map}"
AI="${AI:-}"
GAME="${GAME:-/root/gamedata}"
RELAY_IP="${RELAY_IP:-163.5.210.131}"
OUT="${OUT:-/root/8peer-$(date +%Y%m%d-%H%M%S)}"
NETNS=(gx gx2 gx3 gx4 gx5 gx6 gx7 gx8)

say() { printf '%s\n' "$*"; }
die() { printf 'FATAL: %s\n' "$*" >&2; exit 1; }

mkdir -p "$OUT"

# ---------------------------------------------------------------------------------------------
# Preflight. Every check here has a failure mode that otherwise shows up as "no frames simulated"
# an hour later.
# ---------------------------------------------------------------------------------------------
say "=== preflight ==="
[ "$PEERS" -ge 2 ] && [ "$PEERS" -le 8 ] || die "PEERS must be 2..8 (got $PEERS)"
[ -x "$GAME/GeneralsXZH" ] || die "no binary at $GAME/GeneralsXZH"

for ((i = 0; i < PEERS; i++)); do
	ns="${NETNS[$i]}"
	ip netns list | grep -qw "$ns" || die "netns '$ns' missing - see tools/relay/README.md"
done

# pkill -x, never -f: -f matches this script's own command line.
pkill -x GeneralsXZH 2>/dev/null
sleep 2
LEFT="$(ps -eo comm | grep -cx GeneralsXZH)"
[ "$LEFT" = "0" ] || die "$LEFT GeneralsXZH still running"
say "no games running"

# A relay-mode peer cannot share a port table with the relay, so confirm the relay is where we
# think it is rather than discovering the collision as a bind failure.
systemctl is-active --quiet gxrelay || say "WARNING: gxrelay is not active on this host"

for ((i = 0; i < PEERS; i++)); do
	d="$OUT/home$i/GeneralsX/GeneralsZH"
	mkdir -p "$d"
	printf 'RelayAddress = %s\n' "$RELAY_IP" > "$d/Options.ini"
done
say "provisioned $PEERS per-peer data dirs (no RelayRoom, no LocalVirtualIP)"
say "map: $MAP"
say ""

# NOTE: -lanmap is passed by the CALLER, and only for the host. A joiner takes the map from the
# host's game options; telling a joiner which map to load would also mask the map-transfer path,
# which is the whole point of a separate test.
launch() {	# launch <index> <netns> <extra args...>
	local i="$1" ns="$2"; shift 2
	setsid nohup ip netns exec "$ns" env \
		CNC_GENERALS_ZH_PATH="$GAME" XDG_DATA_HOME="$OUT/home$i" \
		${ROOM:+GENERALSX_LANROOM="$ROOM"} \
		"$GAME/GeneralsXZH" -headless "$@" \
		-lanframes "$FRAMES" -lantimeout 1800000 \
		> "$OUT/peer$i.out" 2> "$OUT/peer$i.err" < /dev/null &
	echo $!
}

# ---------------------------------------------------------------------------------------------
# Host first, then read the room it generated. The joiners cannot browse for it reliably here:
# addresses are per room, so every host is 10.42.0.1, and with one game listed that is fine - but
# pinning removes a retry loop from the middle of an eight-way start-up race.
# ---------------------------------------------------------------------------------------------
ROOM=""
say "=== starting host in ${NETNS[0]} ==="
HOST_PID="$(launch 0 "${NETNS[0]}" -lanhost eightpeer -lanwait "$((PEERS - 1))" \
	-lanmap "$MAP" ${AI:+-lanai "$AI"})"
say "host pid $HOST_PID"

for _ in $(seq 1 60); do
	ROOM="$(grep -ao "in room [a-z0-9]*" "$OUT/peer0.err" 2>/dev/null | head -1 | awk '{print $3}')"
	[ -n "$ROOM" ] && break
	kill -0 "$HOST_PID" 2>/dev/null || die "host died before it registered - see $OUT/peer0.err"
	sleep 2
done
[ -n "$ROOM" ] || die "host never reported a room - see $OUT/peer0.err"
say "host room: $ROOM"
say ""

say "=== starting $((PEERS - 1)) joiners ==="
PIDS=("$HOST_PID")
for ((i = 1; i < PEERS; i++)); do
	p="$(launch "$i" "${NETNS[$i]}" -lanjoin 10.42.0.1)"
	PIDS+=("$p")
	say "  peer$i in ${NETNS[$i]} -> pid $p"
	sleep 1		# stagger: eight simultaneous GXWHO bursts are a needless race on assignment
done

say ""
say "=== waiting ==="
for p in "${PIDS[@]}"; do
	while kill -0 "$p" 2>/dev/null; do sleep 5; done
done
say "all peers exited"
say ""

# ---------------------------------------------------------------------------------------------
# Results. Report the distinct-CRC count next to every diff: an earlier "identical" run in this
# project had three distinct values across 600 frames, because two idle bases did nothing.
# ---------------------------------------------------------------------------------------------
say "=== streams ==="
SHORTEST=0
for ((i = 0; i < PEERS; i++)); do
	grep -a '^\[GXCRC\]' "$OUT/peer$i.err" | tr -d '\r' > "$OUT/peer$i.crc"
	n=$(wc -l < "$OUT/peer$i.crc" | tr -d ' ')
	k=$(awk '{print $3}' "$OUT/peer$i.crc" | sort -u | wc -l | tr -d ' ')
	printf '  peer%d  frames=%-6s distinct=%-6s md5=%s\n' \
		"$i" "$n" "$k" "$(md5sum < "$OUT/peer$i.crc" | cut -d' ' -f1)"
	if [ "$n" -eq 0 ]; then
		say "    FAIL: simulated nothing"
		grep -a -m1 'UDP::Bind failed\|transportInit=FAILED\|build mismatch' "$OUT/peer$i.err" |
			sed 's/^/    /'
	fi
	# Written out rather than as `[ A ] || [ B ] && C`, which parses as `(A || B) && C` and is one
	# edit away from being silently wrong.
	if [ "$SHORTEST" -eq 0 ] || [ "$n" -lt "$SHORTEST" ]; then
		SHORTEST="$n"
	fi
done

say ""
say "=== pairwise, on the CRC VALUE column ==="
# NOT `paste a b | awk '$2!=$4'` - paste renumbers the fields, so $2 is compared against the other
# file's tag and every row "differs". Compare $3 against $6.
PAIRS=0
BAD=0
for ((i = 0; i < PEERS; i++)); do
	for ((j = i + 1; j < PEERS; j++)); do
		head -n "$SHORTEST" "$OUT/peer$i.crc" > "$OUT/.a"
		head -n "$SHORTEST" "$OUT/peer$j.crc" > "$OUT/.b"
		d=$(paste "$OUT/.a" "$OUT/.b" | awk '$3!=$6' | wc -l | tr -d ' ')
		PAIRS=$((PAIRS + 1))
		if [ "$d" -ne 0 ]; then
			BAD=$((BAD + 1))
			say "  peer$i vs peer$j: $d of $SHORTEST DIFFER"
			paste "$OUT/.a" "$OUT/.b" | awk '$3!=$6' | head -2 | sed 's/^/      /'
		fi
	done
done
rm -f "$OUT/.a" "$OUT/.b"

say ""
say "======================================================================"
say " peers          : $PEERS"
say " frames compared: $SHORTEST"
say " pairs compared : $PAIRS"
say " pairs differing: $BAD"
say " results        : $OUT"
say "======================================================================"
[ "$BAD" -eq 0 ] && [ "$SHORTEST" -gt 0 ] &&
	{ say "PASS: $PEERS peers, $SHORTEST frames, all $PAIRS pairs identical"; exit 0; }
say "FAIL"
exit 1
